#%RAML 1.0
title: CredentialsAPI
description: 'This is CredentialsAPI which follow ext standard specification: https://www.w3.org/TR/credential-management/'
version: 0.0.1
mediaType: application/json
protocols:
  - HTTP
baseUri: 'http://localhost/credentialsAPI'
documentation:
  - title: 'this documentation title'
    content: 'Documenation content'



types:
  password-strength:
    description: 'This is password strength DataType'
    type: object
    properties: 
      strength: integer

    
/signin:
  get:
    headers:
      securetoken:
        example: '1.2312324435645647fghfghe22'
        type: string
    description: 'Secured token which stored by browser, used to authenticate in default mode. By filling in the form and pressing the "Sign In" button at the sign-in page (/signin), an AJAX GET is sent to this endpoint. You will then be redirected to the main page (/main) if the request is successful or shown an error message if it fails.'
    responses:
      '200': 
        description: 'The server successfully processed the request.'
      '401': 
        description: 'The user does not have the necessary credentials.'  
      '400': 
        description: 'Bad Request'
    queryParameters:
      uuid:
        minLength: 8
        example: '2345345352342-09w93i53'
        description: 'uuid used to register in system'
        type: string
/signout:
  get:
    headers:
      securetoken:
        example: '1.2312324435645647fghfghe22'
        type: string
    description: 'Secured token which stored by browser, used to authenticate in default mode. By tapping on the "Sign Out" button at the main page, an AJAX request is sent to this endpoint, sign out happened, then redirected to /.'
    
    responses:
      '200': 
        description: 'The server successfully processed the request.'
      '400': 
        description: 'Bad Request'
      '401': 
        description: 'The user does not have the necessary credentials.'

/unregister:
  get:
    headers:
      securetoken:
        example: '1.2312324435645647fghfghe22'
        type: string
    description: 'By tapping on the "Unregister" button at the main page, an AJAX request is sent to this endpoint, unregister, then redirected to /.'
    queryParameters:
      uuid:
        example: '131231242342'
        description: 'This is uuid of user which will be uregistered'
        type: string
    responses:
      '200': 
        description: 'The server successfully processed the request.'
      '401': 
        description: 'The user does not have the necessary credentials.'  
      '400': 
        description: 'Bad Request'


/password-strength:
  get:
    headers:
      password:
        example: 'Abracadabra'
        description: 'How strong passord is'
        type: string
    description: 'By tapping on the "Password" field at the main page, an AJAX request is sent to this endpoint to check how strong the password is. Result is itnteger from 0 to 10 /. Password send in Base64 encoding'
    responses:
      '200':
         body: 
          text/plain:
            description: 'Return secureToken in body'
            type: string
         description: 'The server successfully processed the request. Return secureToken in body as plain text' 
      '204': 
          description: 'The server successfully processed the request and is not returning any content.'
      '401': 
        description: 'The user does not have the necessary credentials.'  
      '400': 
        description: 'Bad Request'
   
/auth-password:
  post:
    headers:
      Authorization:
        example: '1.2312324435645647fghfghe22'
        type: string
    description: 'By filling the form and pressing a "Login" button at the top page (/), the form will send an AJAX POST to this endpoint. Based 64 encoded username:password key pair wil be send "Authorization" header. You will be then redirected to the main page (/main) if the request is successful or will show an error message if it fails.'
    responses:
      '200': 
        body:
         text/plain:
          description: 'Return secureToken in body'
          type: string
        description: 'The server successfully processed the request. Return secureToken in body as plain text'
      '401': 
        description: 'The user does not have the necessary credentials.' 
      '400': 
        description: 'Bad Request'
    
/register:
  post:
    description: 'By filling the form and pressing a "Regiter" button at the top page (/), the form will send an AJAX POST to this endpoint. You will be then redirected to the main page (/main) if the request is successful or will show an error message if it fails.'
    queryParameters:
      username:
        minLength: 8
        example: jira12345
        description: 'This is user name'
        type: string
      password:
        example: P@ssword
        description: 'This alfa-numeric password'
        type: string
    responses:
      '200': 
        body:
         text/plain:
          description: 'Return secureToken in body'
          type: string
        description: 'The server successfully processed the request. Return secureToken in body as plain text'
      '401': 
        description: 'The user does not have the necessary credentials.'  
      '400': 
        description: 'Bad Request'
/oauth: 
  get:
    description: 'By tapping on the "Sygn by others providers" field at the main page, an AJAX request is sent to this endpoint to check other provider request id.'
    queryParameters:
      password:
        example: '223423480294203402'
        description: 'Other provider request id'
        type: string
    responses:
      '200': 
        body:
         text/plain:
          description: 'Return secureToken in body'
          type: string
        description: 'The server successfully processed the request. Return secureToken in body as plain text'
      '204': 
          description: 'The server successfully processed the request and is not returning any content.'
      '401': 
        description: 'The user does not have the necessary credentials.'  
      '400': 
        description: 'Bad Request'
